config/routes.rb
PHA::Application.routes.draw do

  resources :equipment

  resources :offices
  match '/servers/list_ood', :controller => 'servers', :action => 'list_ood', :as => "ood_servers"
  match '/servers/list_utd', :controller => 'servers', :action => 'list_utd', :as => "utd_servers"

  match '/softwares/list_ood', :controller => 'softwares', :action => 'list_ood', :as => "ood_softwares"
  match '/softwares/list_utd', :controller => 'softwares', :action => 'list_utd', :as => "utd_softwares"

  resources :servers do
    get :associate, :on => :member
    get :addassociation, :on => :member
    get :disassociate, :on => :member
    resources :softwares 
  end

  resources :softwares do
    get :associate, :on =>  :member
    get :addassociation, :on => :member
    get :disassociate, :on => :member
    resources :servers
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :gwaddr, :iosi, :iosu, :iosv, :ipseg, :mgmtip, :name, :notes, :serial, :wanip
  validates :serial => :presence=true
  belongs_to :office
  accepts_nested_attributes_for :office
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @equipment }
    end
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @equipment }
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = Equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, :notice => 'Equipment was successfully created.' }
        format.json { render :json => @equipment, :status => :created, :location => @equipment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @equipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, :notice => 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @equipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= form_for(@equipment) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :serial %><br />
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :iosv %><br />
    <%= f.text_field :iosv %>
  </div>
  <div class="field">
    <%= f.label :iosi %><br />
    <%= f.text_field :iosi %>
  </div>
  <div class="field">
    <%= f.label :ipseg %><br />
    <%= f.text_field :ipseg %>
  </div>
  <div class="field">
    <%= f.label :gwaddr %><br />
    <%= f.text_field :gwaddr %>
  </div>
  <div class="field">
    <%= f.label :wanip %><br />
    <%= f.text_field :wanip %>
  </div>
  <div class="field">
    <%= f.label :mgmtip %><br />
    <%= f.text_field :mgmtip %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :iosu %><br />
    <%= f.text_field :iosu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<h1>Listing equipment</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Serial</th>
    <th>Iosv</th>
    <th>Iosi</th>
    <th>Ipseg</th>
    <th>Gwaddr</th>
    <th>Wanip</th>
    <th>Mgmtip</th>
    <th>Notes</th>
    <th>Iosu</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.name %></td>
    <td><%= equipment.serial %></td>
    <td><%= equipment.iosv %></td>
    <td><%= equipment.iosi %></td>
    <td><%= equipment.ipseg %></td>
    <td><%= equipment.gwaddr %></td>
    <td><%= equipment.wanip %></td>
    <td><%= equipment.mgmtip %></td>
    <td><%= equipment.notes %></td>
    <td><%= equipment.iosu %></td>
    <td><%= link_to 'Show', equipment %></td>
    <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Destroy', equipment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @equipment.name %>
</p>

<p>
  <b>Serial:</b>
  <%= @equipment.serial %>
</p>

<p>
  <b>Iosv:</b>
  <%= @equipment.iosv %>
</p>

<p>
  <b>Iosi:</b>
  <%= @equipment.iosi %>
</p>

<p>
  <b>Ipseg:</b>
  <%= @equipment.ipseg %>
</p>

<p>
  <b>Gwaddr:</b>
  <%= @equipment.gwaddr %>
</p>

<p>
  <b>Wanip:</b>
  <%= @equipment.wanip %>
</p>

<p>
  <b>Mgmtip:</b>
  <%= @equipment.mgmtip %>
</p>

<p>
  <b>Notes:</b>
  <%= @equipment.notes %>
</p>

<p>
  <b>Iosu:</b>
  <%= @equipment.iosu %>
</p>


<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>