config/routes.rb
PHA::Application.routes.draw do

  resources :equipment

  resources :offices
  match '/servers/list_ood', :controller => 'servers', :action => 'list_ood', :as => "ood_servers"
  match '/servers/list_utd', :controller => 'servers', :action => 'list_utd', :as => "utd_servers"

  match '/softwares/list_ood', :controller => 'softwares', :action => 'list_ood', :as => "ood_softwares"
  match '/softwares/list_utd', :controller => 'softwares', :action => 'list_utd', :as => "utd_softwares"

  resources :servers do
    get :associate, :on => :member
    get :addassociation, :on => :member
    get :disassociate, :on => :member
    resources :softwares 
  end

  resources :softwares do
    get :associate, :on =>  :member
    get :addassociation, :on => :member
    get :disassociate, :on => :member
    resources :servers
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :name, :os, :phys
  validates :name, :presence => true
  has_and_belongs_to_many :softwares
  accepts_nested_attributes_for :softwares

  def self.search(search)
     if search
        find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
     else
        find(:all)
     end
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  http_basic_authenticate_with :name => "Administrator", :password => "PHARails"
  # GET /servers
  # GET /servers.json

  before_filter :get_server, :only => [:show, :edit, :update, :destroy, :associate, :addassociation, :disassociate]
  before_filter :get_servers, :only => [:list_ood, :list_utd]

  def get_server
    @server = Server.find(params[:id])
  end

  def get_servers
    @servers = Server.find(:all)
  end

  def index
    @servers = Server.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, :notice => 'Server was successfully created.' }
        format.json { render :json => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, :notice => 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end

  def list_ood
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  def list_utd
    respond_to do |format|
      format.html
      format.json { render :json => @server }
    end
  end

  def associate
    #@server.softwares << software
    @softwares = Software.find(:all)
    respond_to do |format|
      format.html
      format.json { render :json => @server }
    end
  end

  def addassociation
    @software = Software.find(params[:format])
    @server.softwares << @software
    redirect_to @server
  end

  def disassociate
    @software = Software.find(params[:format])
    @server.softwares.delete(@software)
    redirect_to @server
  end

  def add_software

  end
    
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label 'Operating System' %><br />
    <%= f.text_field :os %>
  </div>

  <div class="field">
    <%= f.label 'Physical/Virtual' %><br />
    <%= f.radio_button :phys, "PHYS" %>
    <%= f.label :phys, "Physical", :value => "PHYS" %>
    <%= f.radio_button :phys, "VM" %>
    <%= f.label :phys, "Virtual Machine", :value => "VM" %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Server', :class => 'save-button' %>
  </div>

<% end %>

app/views/servers/associate.html.erb
<h2>Add Component to <%= @server.name %></h2>

<div class="softwares-table">

<div class="table-head">
	<div class="cell software-cell-name">
		Component Name
	</div>
	
	<div class="cell software-cell-status">
		Status
	</div>

	<div class="cell software-cell-version">
		Version
	</div>
</div>

<div class="clear">
</div>

<%for software in @softwares %>
	<%if not @server.softwares.include?(software) %>
		<%if software.status.include?("Out of date")%>
			<div class="ood-software">
		<%else%>
			<div class="utd-software">
		<%end%>
		<div class="cell software-cell-name">
			<%=software.name%>
		</div>
		<div class="cell software-cell-status">
			<%=software.status%>
		</div>
		<div class="cell software-cell-version">
			<%=software.version%>
		</div>
		<div class="cell software-cell-link">
			<%=link_to 'Add', addassociation_server_path(@server, software) %>
		</div>
		<div class="cell software-cell-link">
			<%=link_to "Edit", edit_server_software_path(@server, software)%>
		</div>
		<div class="cell software-cell-link">
			<%=link_to 'Delete', server_software_path(@server, software), :confirm => 'Are you sure?', :method => :delete %>
		</div>
		<div class="clear">
		</div>

		</div>
	<%end%>
<%end%>
</div>

<%= link_to 'List Servers', servers_path %> |
<%= link_to 'Back to Server', @server %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>

<body>

<h1>Listing servers</h1>

<%= form_tag servers_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>

<div class="buttons-container">
<%= button_to "Show All", servers_path, :method => 'get', :class => 'sort-button'%>
<%= button_to "Out of date", ood_servers_path, :action => 'list_ood', :method => 'get', :class => 'sort-button' %>
<%= button_to "Up to date", utd_servers_path, :method => 'get', :class => 'sort-button' %>
</div>

<div class="clear">
</div>

<%= link_to "Add Server", new_server_path, :class => "bottom-button" %>

<div class="servers-table">
<div class="table-head">
	<div class="cell cell-name">
		Name
	</div>
	<div class="cell cell-os">
		OS
	</div>
	<div class="cell cell-phys">
		Phys
	</div>
</div>

<div class="clear">
</div>

<% for server in @servers %>
  <% # This block of code determines if the server has any out of date software, and flags the listing red if any is found. %>
  <% softwares = server.softwares.where(:status => "Out of date") %>
  <% if not softwares.empty? %>
  <div class="ood">
  <% else %>
  <div class="utd">
  <%end%>
  <% # End the check for out-of-date flag %>

	  <div class="cell cell-name">
	    <%= server.name %>
	  </div>

	  <div class="cell cell-os">
	    <%= server.os %>
	  </div>

	  <div class="cell cell-phys">
	    <%= server.phys %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Show', server %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Edit', edit_server_path(server) %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %>
	  </div>

	  <div class="clear">
	  </div>
   </div>
<% end %>
</div>

</body>

app/views/servers/list_ood.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>

<body>

<h1>Listing servers</h1>

<%= form_tag servers_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>

<div class="buttons-container">
<%= button_to "Show All", servers_path, :method => 'get', :class => 'sort-button'%>
<%= button_to "Out of date", ood_servers_path, :action => 'list_ood', :method => 'get', :class => 'sort-button' %>
<%= button_to "Up to date", utd_servers_path, :method => 'get', :class => 'sort-button' %>
</div>

<div class="clear">
</div>

<%= link_to "Add Server", new_server_path, :class => "bottom-button" %>


<div class="servers-table">
<div class="table-head">
	<div class="cell cell-name">
		Name
	</div>
	<div class="cell cell-os">
		OS
	</div>
	<div class="cell cell-phys">
		Phys
	</div>
</div>
<br />

<% for server in @servers %>
  <% softwares = server.softwares.where(:status => "Out of date") %>
  <% if not softwares.empty? %>
	<div class="ood">
		<div class="cell cell-name">
			<%= server.name %>
		</div>

		<div class="cell cell-os">
			<%= server.os %>
		</div>

		<div class="cell cell-phys">
			<%= server.phys %>
		</div>

		<div class="cell cell-link">
			<%= link_to 'Show', server %>
		</div>

		<div class="cell cell-link">
			<%= link_to 'Edit', edit_server_path(server) %>
		</div>

		<div class="cell cell-link">
			<%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %>
		</div>

		<div class="clear">
		</div>
	</div>
  <% end %>
<% end %>
</div>

</body>

app/views/servers/list_utd.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>

<body>

<h1>Listing servers</h1>

<%= form_tag servers_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>

<div class="buttons-container">
<%= button_to "Show All", servers_path, :method => 'get', :class => 'sort-button'%>
<%= button_to "Out of date", ood_servers_path, :action => 'list_ood', :method => 'get', :class => 'sort-button' %>
<%= button_to "Up to date", utd_servers_path, :method => 'get', :class => 'sort-button' %>
</div>


<div class="clear">
</div>

<%= link_to "Add Server", new_server_path, :class => "bottom-button" %>

<div class="servers-table">
<div class="table-head">
	<div class="cell cell-name">
		Name
	</div>
	<div class="cell cell-os">
		OS
	</div>
	<div class="cell cell-phys">
		Phys
	</div>
</div>

<div class="clear">
</div>

<% for server in @servers %>
  <% softwares = server.softwares.where(:status => "Out of date") %>
  <% if softwares.empty? %>
  <div class="utd">
	<div class="cell cell-name">
    		<%= server.name %>
	</div>

	<div class="cell cell-os">
		<%= server.os %>
	</div>
	
	<div class="cell cell-phys">
		<%= server.phys %>
	</div>

	<div class="cell cell-link">
		<%= link_to 'Show', server %>
	</div>

	<div class="cell cell-link">
		<%= link_to 'Edit', edit_server_path(server) %>
	</div>

	<div class="cell cell-link">
		<%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %>
	</div>

	<div class="clear">
	</div>
  </div>
  <%end%>
<% end %>
</div>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @server.name %></h1>

<h2><%= @server.os %></h2>

<h3>
<%if @server.phys.include?("VM") %>
	Virtual Machine
<%else%>
	Physical Server
<%end%>
</h3>

<%=button_to 'Add Component', associate_server_path(@server), :class => 'add-button', :method => :get %>

<div class="clear">
</div>

<%= link_to "Edit Server", edit_server_path(@server), :class => "bottom-button" %>
<%= link_to "Back to All Servers", servers_path, :class => "bottom-button" %>

<div class="softwares-table">

<div class="table-head">
	<div class="cell software-cell-name">
		Software Name
	</div>
	
	<div class="cell software-cell-status">
		Status
	</div>

	<div class="cell software-cell-version">
		Version
	</div>
</div>

<div class="clear">
</div>


<%# softwares = [@server.softwares] %>
<%for software in @server.softwares %>  
<%# for software in softwares %>
	<%if software.status.include?("Out of date")%>
		<div class="ood-software">
	<%else%>
		<div class="utd-software">
	<%end%>
	<div class="cell software-cell-name">
		<%=software.name%>
	</div>
	<div class="cell software-cell-status">
		<%=software.status%>
	</div>
	<div class="cell software-cell-version">
		<%=software.version%>
	</div><!---
	<div class="cell software-cell-link">
		<%=link_to "Show", server_software_path(@server, software)%>
	</div>--->

	<div class="cell software-cell-link">
		<%=link_to "Show", server_software_path(@server, software)%>
	</div>

	<div class="cell software-cell-link">
		<%=link_to "Edit", edit_server_software_path(@server, software)%>
	</div>
	<div class="cell software-cell-link">
		<%=link_to 'Remove', disassociate_server_path(@server, software), :confirm => 'Are you sure?' %>
	</div>
	<div class="clear">
	</div>

	</div>
<%end%>
</div>