config/routes.rb
PHA::Application.routes.draw do

  resources :equipment

  resources :offices
  match '/servers/list_ood', :controller => 'servers', :action => 'list_ood', :as => "ood_servers"
  match '/servers/list_utd', :controller => 'servers', :action => 'list_utd', :as => "utd_servers"

  match '/softwares/list_ood', :controller => 'softwares', :action => 'list_ood', :as => "ood_softwares"
  match '/softwares/list_utd', :controller => 'softwares', :action => 'list_utd', :as => "utd_softwares"

  resources :servers do
    get :associate, :on => :member
    get :addassociation, :on => :member
    get :disassociate, :on => :member
    resources :softwares 
  end

  resources :softwares do
    get :associate, :on =>  :member
    get :addassociation, :on => :member
    get :disassociate, :on => :member
    resources :servers
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/software.rb
class Software < ActiveRecord::Base
  has_and_belongs_to_many :servers
  accepts_nested_attributes_for :servers
  attr_accessible :name, :status, :version
  validates :name, :presence => true
  validates :status, :presence => true

  def self.search(search)
     if search
        find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
     else
        find(:all)
     end
  end
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  http_basic_authenticate_with :name => "Administrator", :password => "PHARails"

   before_filter :get_software, :only => [:show, :edit, :update, :destroy, :associate, :addassociation, :disassociate]
   before_filter :get_softwares, :only => [:list_ood, :list_utd]

  def get_software
    @software = Software.find(params[:id])
  end

  def get_softwares
    @softwares = Software.find(:all)
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @software }
    end
  end


  def index
    @softwares = Software.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @softwares }
    end
  end

  def new
    @software = Software.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  def edit
  end

  def create
    @software = Software.new(params[:software])

    respond_to do |format|
      @server
      if @software.save
        format.html { redirect_to @software, :notice => 'Server was successfully created.' }
        format.json { render :json => @software, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.json { render :json => @software.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
   # @software = Software.find(params[:id])
   # @server = @software.server

    respond_to do |format|
      if @software.update_attributes(params[:software])
        format.html { redirect_to @software, :notice => 'Componenet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @software.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url }
      format.json { head :no_content }
      end
  end

  def list_ood
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @software }
    end
  end

  def list_utd
    respond_to do |format|
      format.html
      format.json { render :json => @software }
    end
  end

  def associate
    #@server.softwares << software
    @servers = Server.find(:all)
    respond_to do |format|
      format.html
      format.json { render :json => @server }
    end
  end

  def addassociation
    @server = Server.find(params[:format])
    @software.servers << @server
    redirect_to @software
  end

  def disassociate
    @server = Server.find(params[:format])
    @software.servers.delete(@server)
    redirect_to @software
  end

end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_form.html.erb
<%= form_for ([@server, @software]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.radio_button :status, "Out of date" %> 
    <%= f.label :status, "Out of date", :value => "Out of date", :class => 'radio' %>
    <%= f.radio_button :status, "Up to date" %>
    <%= f.label :status, "Up to date", :value => "Up to date", :class => 'radio' %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Add Component', :class => 'save-button' %>
  </div>
<% end %>

app/views/softwares/_software.html.erb
<p>
  <b>Name:</b>
  <%= software.name %>
</p>
 
<p>
  <b>Version:</b>
  <%= software.version %>
</p>

<p>
  <b>Status: </b>
  <%= software.status %>
</p>

<p>
  <b> ID: </b>
  <%= software.id %>
</p>

<p>
  <b> Server ID: </b>
  <%= software.server_id %>
</p>

<p>
   <%= button_to 'Edit', edit_server_software_path(@server, software), :method => :get%>
</p>

<p>
   <%= button_to 'Remove', [@server, software], :confirm => "Are you sure?", :method => :delete %>
</p>
<!--

   <p>
    <table>
    <tr>
    <td> Name </td>
    <td> Version </td>
    <td> Status </td>
    </tr>
<% @server.softwares.each do |software| %>
    <tr>
    <td> <%=software.name%> </td>
    <td> <%=software.version%> </td>
    <td> <%=software.status%> </td>
    <td> <%= button_to('Remove', @software, :confirm => 'Are you sure?', :method => :delete) %></td>

    </tr>
<% end %>
    </table>

-->

app/views/softwares/associate.html.erb
<h2>Add Server to <%= @software.name %></h2>

<div class="servers-table">

<div class="table-head">
	<div class="cell cell-name">
		Server Name
	</div>
	
	<div class="cell cell-os">
		OS
	</div>

	<div class="cell cell-phys">
		Phys
	</div>
</div>

<div class="clear">
</div>

<%for server in @servers %>
	<%if not @software.servers.include?(server) %>
		<% softwares = server.softwares.where(:status => "Out of date") %>
		<%if not softwares.empty?%>
			<div class="ood">
		<%else%>
			<div class="utd">
		<%end%>
		<div class="cell cell-name">
			<%=server.name%>
		</div>
		<div class="cell cell-os">
			<%=server.os%>
		</div>
		<div class="cell cell-phys">
			<%=server.phys%>
		</div>
		<div class="cell link">
			<%=link_to 'Add', addassociation_software_path(@software, server) %>
		</div>
		<div class="cell cell-link">
			<%=link_to "Edit", edit_software_server_path(@software, server)%>
		</div>
		<div class="cell cell-link">
			<%=link_to 'Delete', software_server_path(@software, server), :confirm => 'Are you sure?', :method => :delete %>
		</div>
		<div class="clear">
		</div>

		</div>
	<%end%>
<%end%>
</div>

<%= link_to 'List Components', softwares_path %> |
<%= link_to 'Back to Component', @software %>

app/views/softwares/edit.html.erb
<h1>Editing Component</h1>

<%= form_for ([:server, @software]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>

  <div class="field">
    <%= f.label :status %> <br />
    <%= f.radio_button :status, "Out of date" %> 
    <%= f.label :status, "Out of date", :value => "Out of date", :class => 'radio' %>
    <%= f.radio_button :status, "Up to date" %>
    <%= f.label :status, "Up to date", :value => "Up to date", :class => 'radio' %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Update Component', :class => 'save-button' %>
  </div>
<% end %>

<%= link_to 'back', software_path(@software) %>

app/views/softwares/index.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>

<body>

<h1>Listing Components</h1>

<%= form_tag softwares_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>

<div class="buttons-container">
<%= button_to "Show All", softwares_path, :method => 'get', :class => 'sort-button'%>
<%= button_to "Out of date", ood_softwares_path, :action => 'list_ood', :method => 'get', :class => 'sort-button' %>
<%= button_to "Up to date", utd_softwares_path, :method => 'get', :class => 'sort-button' %>
</div>

<div class="clear">
</div>

<%= link_to "Add New Component", new_software_path, :class => "bottom-button" %>

<div class="softwares-table">
<div class="table-head">
	<div class="cell software-cell-name">
		Name
	</div>
	<div class="cell software-cell-status">
		Status
	</div>
	<div class="cell software-cell-version">
		Version
	</div>
</div>

<div class="clear">
</div>

<%for software in @softwares %>  
	<%if software.status.include?("Out of date")%>
		<div class="ood-software">
	<%else%>
		<div class="utd-software">
	<%end%>
  <% # End the check for out-of-date flag %>

	  <div class="cell software-cell-name">
	    <%= software.name %>
	  </div>

	  <div class="cell software-cell-status">
	    <%= software.status %>
	  </div>

	  <div class="cell software-cell-version">
	    <%= software.version %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Show', software %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Edit', edit_software_path(software) %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Destroy', software, :confirm => 'Are you sure?', :method => :delete %>
	  </div>

	  <div class="clear">
	  </div>
   </div>
<% end %>
</div>

</body>

app/views/softwares/list_ood.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>

<body>

<h1>Listing Components</h1>

<%= form_tag servers_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>

<div class="buttons-container">
<%= button_to "Show All", softwares_path, :method => 'get', :class => 'sort-button'%>
<%= button_to "Out of date", ood_softwares_path, :action => 'list_ood', :method => 'get', :class => 'sort-button' %>
<%= button_to "Up to date", utd_softwares_path, :method => 'get', :class => 'sort-button' %>
</div>

<div class="clear">
</div>

<%= link_to "Add New Component", new_software_path, :class => "bottom-button" %>

<div class="softwares-table">
<div class="table-head">
	<div class="cell software-cell-name">
		Name
	</div>
	<div class="cell software-cell-status">
		Status
	</div>
	<div class="cell software-cell-version">
		Version
	</div>
</div>

<div class="clear">
</div>

<% for software in @softwares %>
  <% if software.status.include?("Out of date") %>
	<div class="ood">	  
		  <div class="cell software-cell-name">
		    <%= software.name %>
		  </div>

		  <div class="cell software-cell-status">
		    <%= software.status %>
		  </div>

		  <div class="cell software-cell-version">
		    <%= software.version %>
		  </div>

		  <div class="cell-link">
		    <%= link_to 'Show', software %>
		  </div>

		  <div class="cell-link">
		    <%= link_to 'Edit', edit_software_path(software) %>
		  </div>

		  <div class="cell-link">
		    <%= link_to 'Destroy', software, :confirm => 'Are you sure?', :method => :delete %>
		  </div>

		  <div class="clear">
		  </div>
	</div>
  <% end %>
<% end %>
</div>
</body>

app/views/softwares/list_utd.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>

<body>

<h1>Listing Components</h1>

<%= form_tag servers_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>

<div class="buttons-container">
<%= button_to "Show All", softwares_path, :method => 'get', :class => 'sort-button'%>
<%= button_to "Out of date", ood_softwares_path, :action => 'list_ood', :method => 'get', :class => 'sort-button' %>
<%= button_to "Up to date", utd_softwares_path, :method => 'get', :class => 'sort-button' %>
</div>

<div class="clear">
</div>

<%= link_to "Add New Component", new_software_path, :class => "bottom-button" %>

<div class="softwares-table">
<div class="table-head">
	<div class="cell software-cell-name">
		Name
	</div>
	<div class="cell software-cell-status">
		Status
	</div>
	<div class="cell software-cell-version">
		Version
	</div>
</div>

<div class="clear">
</div>

<% for software in @softwares %>
  <% if not software.status.include?("Out of date") %>
	<div class="utd">	  
		  <div class="cell software-cell-name">
		    <%= software.name %>
		  </div>

		  <div class="cell software-cell-status">
		    <%= software.status %>
		  </div>

		  <div class="cell software-cell-version">
		    <%= software.version %>
		  </div>

		  <div class="cell-link">
		    <%= link_to 'Show', software %>
		  </div>

		  <div class="cell-link">
		    <%= link_to 'Edit', edit_software_path(software) %>
		  </div>

		  <div class="cell-link">
		    <%= link_to 'Destroy', software, :confirm => 'Are you sure?', :method => :delete %>
		  </div>

		  <div class="clear">
		  </div>
	</div>
  <% end %>
<% end %>
</div>

</body>

app/views/softwares/new.html.erb
<h1>New Component</h1>

<%= render 'form' %>

<%= link_to 'back', softwares_path %>

app/views/softwares/show.html.erb
<p id="notice"><%= notice %></p>
 
<h1><%= @software.name %></h1>

<%if @software.status.include?("Out of date") %>
<h2 class="ood">
<% else %>
<h2>
<% end %>
<%= @software.status %></h2>
 
<h3>Version <%= @software.version %></h3> 

<%=button_to 'Add Server', associate_software_path(@software), :class => 'add-button', :method => :get %>

<div class="clear">
</div>


<%= link_to "Edit Component", edit_software_path(@software), :class => "bottom-button" %>
<%= link_to "Back to All Components", softwares_path, :class => "bottom-button" %>

<div class="servers-table">
<div class="table-head">
	<div class="cell cell-name">
		Server Name
	</div>
	<div class="cell cell-os">
		OS
	</div>
	<div class="cell cell-phys">
		Phys
	</div>
</div>

<div class="clear">
</div>

<% servers = @software.servers %>
<% for server in servers %>
  <% softwares = server.softwares.where(:status => "Out of date") %>
  <% if not softwares.empty? %>
  <div class="ood">
  <% else %>
  <div class="utd">
  <%end%>
  <% # End the check for out-of-date flag %>

	  <div class="cell cell-name">
	    <%= server.name %>
	  </div>

	  <div class="cell cell-os">
	    <%= server.os %>
	  </div>

	  <div class="cell cell-phys">
	    <%= server.phys %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Show', server %>
	  </div>

	  <div class="cell-link">
	    <%= link_to 'Edit', edit_server_path(server) %>
	  </div>

	  <div class="cell-link">
		<%=link_to 'Remove', disassociate_software_path(@software, server), :confirm => 'Are you sure?' %>
	  </div>

	  <div class="clear">
	  </div>
   </div>
<% end %>
</div>